lists = {
    "goats": [
        # From https://www.reddit.com/r/sysadmin/comments/4l7kjd/found_a_text_file_at_work_titled_why_should_i/
        "you don't have to monitor the utilization on a goat.",
        "milk a goat and the goat stays milked for a while.",
        "there are no 32-bit goats.",
        "you don't have to do a demo on a goat. and if you ever do, the goat will do what it's supposed to do and there's not a lot that can keep it from doing it.",
        "when a goat goes \"down\", you just bury it and buy a new goat.",
        "left alone, billy goats and nanny goats do what they're supposed to do. you don't need to format them, monitor them, be on-call for them, step, trace or inspect registers.",
        "nobody cares if you're not a certified goat engineer yet.",
        "kill a goat to make a goat steak, and the goat stays dead.",
        "most people will take advice from a goat farmer on how to paint a fence, cook a steak, fix a tractor, etc. but most people somehow just don't want to hear it from a computer weenie.",
        "nobody can lie in a job interview about their goat experience.",
        "goats don't page you.",
        "when it comes to \"software\" (food), everything is compatible with a goat.",
        "you don't need to buy a \"goat 98\" to fix all the bugs in your goat 95",
        "you can tell whether a goat has been \"debugged\" by looking at it.",
        "goats don't become obsolete. if they do, as long as you didn't neuter them, they make the necessary upgrades themselves.",
        "no commute.",
        "goats are kind of cute. computers aren't cute unless they're macintoshes, and those are just plain annoying.",
        "no dress code. of any kind. ever.",
        "you always have the right \"file permissions\" to milk a goat.",
        "if a goat gives too many timeout errors, or does not avail you resources for your session, or if performance is generally slow for your applications on your goat, it just means you're having goat steak for dinner.",
        "you don't need to visit \"shareware dot com\" to get some tools to milk a goat. you either have your bucket or you don't.",
        "the bucket leaks, or it doesn't. you do not need to ask a network if you're still the owner of the bucket. you do not need to run a bucket compare against a copy you made of the bucket previously you couldn't care less about the checksum of the bucket.",
        "you don't need to \"free up some megs\" before you milk a goat.",
        "you get callouses on your hands - the way god intended!",
        "you don't need to call a staff meeting to make sure everyone's milking goats the same way.",
        "nanny goats, with no tcp/ip stack loaded, and no dlc, still give milk.",
        "just about any barnyard animal is fault tolerant (except some cows).",
        "you don't need to sign in with the front desk if you need to milk a goat on a weekend. you don't need to use a badge to open a front gate. if you find an empty coffee pot burning on the machine on a saturday, you just yell at your wife.",
        "you don't need to worry if you've been spending a lot of time milking what you will later find out to have been an improperly labelled \"development goat\".",
        "there is no such thing as a \"preferred goat,\" and your \"goat context\" is always correct. passwords do not exist and your milking/slaughtering account will never be disabled because of intruder detection.",
        "carpal tunnel is guaranteed. don't worry about it.",
        "a goat has all the \"patches\" it will ever need. if it doesn't it just means you're having goat steak for dinner.",
        "goats that become full do an automatic \"core dump\" but they take care of getting themselves reset and on-line. you just have to clean up. you do not need to worry about defragmenting or compressing the goat. the goat does not have to be zipped, archived or converted to goat-32.",
        "as long as the stable hasn't caught fire, a goat couldn't care less about a power surge.",
        "goats don't have to be backed up at night.",
        "each and every one of the parts of a goat use the same interrupt, and the goat works just fine anyway.",
        "a goat is a goat is a goat.",
        "you don't ever restart a goat. you do shut them down sometimes and it's the first step in many of your recipes.",
        "nobody ever needed to draft up a goat-milking requirements document.",
        "you deliver applications to goats. goats do not deliver applications to you.",
        "a goat will do practically anything do get more comfortable. computers have been known to display the same error message over and over again, all day, without regard to how frequently or how hard the monitor has been hit, slapped, punched or kicked.",
        "you don't have to log off of a goat and listen to some silly \"exit goat\" sound effect for the next several minutes.",
        "you won't find out from your next phone bill that you milked your goat too much for your budget.",
        "on a goat, the sys$err.log file is always empty.",
        "operating systems come & go, but goats will probably never be \"orphaned\" as they are expected to be produced by their manufacturer for quite some time to come.",
        "there are no workstation licensing issues with goats.",
        "you don't get in trouble for milking a goat during business hours, and nobody cares if you reformat it.",
        "if it's late and you have a lot of goat-milking to do, at least you can see your kids before they have to go to bed. you can probably even make them help you milk your goats.",
        "you don't need 32 megs of ram to get started milking your goat.",
        "goat security is applied completely, thoroughly, and with all the features you'll ever need, using a stake and a rope.",
        "nobody ever got a general protection fault milking a goat.",
        "you don't need to worry about your whole goat herd locking up if you put an ethernet goat and a token-ring goat together in the same stable.",
        "you don't name goats. if you do name goats, you can give two or more goats the same name and this will not interfere with your ability to access any of the goats.",
        "your kids will not meet some pervert who wants to buy them a bus ticket when they play with a goat.",
        "there is no closely-watched dispute between microsoft and any competitor, over who will dominate the goat-milking product industry. you will probably never be asked to check-mark a box that says, make this my default goat-milking bucket.",
        "you do not want, need, or desire in any way for goats to run at a higher clock speed. and they don't.",
        "you do not need to use a wrist strap to ground yourself before milking, and there's never a need to put your goat in a little plastic baggie. unless making goat steak",
        "there really aren't too many ways to improperly shut down a goat.",
        "surrounded by a room full of younger goat farmers, you don't need to worry about dating yourself talking about 300-baud or 4.7-mhz goats.",
        "y2k.",
        "you do not need to buy anything to \"uninstall\" a goat. maybe a gun or a knife.",
        "once you've filled a bucket with goat milk, the goat can crash and it doesn't matter whether you've \"saved\" or not. just don't spill.",
        "when you buy a new goat, the goat does not need to re-write registry keys on the farm that could have unforeseen effects on the other animals already residing there.",
        "there are no easter eggs in a goat.",
        "you never need to learn goat 2000, goat perfect 8, or goat 123",
        "you don't need an internal ipx address to boot a goat.",
        "goats don't need a per-bucket license.",
        "you will never spend 4 hours upgrading a goat over the wire.",
        "there is no goat ops.",
        "goats follow upgrade procedures.",
        "goats eat org charts.",
        "if a goat gets an uncleanable virus, you shoot it.",
        "if a goat has a non-terminal virus it just does the poo-poo.",
        "goats don't need pagers and never get a 'please advise'.",
        "goats don't have to worry about whether or not it's calcomp.",
        "a goat farmer doesn't care if people can't remotely access his herd.",
        "no mhn goat herd.",
        "no one gives a rat's ass if the goats aren't talking to each other.",
        "ever heard of a proprietary goat?",
        "no goat analysis meetings.",
        "no goat control meetings.",
        "no meetings.",
        "goats will never need service pack 4.",
        "fuck y2k.",
        "goats don't ever ask stupid questions.",
        "goats don't drive technology dollars away from your automobile lusts.",
        "if a goat takes a \"dump\" in the middle of the night, you take care of it when you damn well feel like it.",
        "nobody will fire you for connecting \"diskless goats\" into a \"goat server\" when they think you should have purchased a massive mainframe goat to connect to a multitude of inexpensive \"dumb goats\".",
        "iso is not publishing any standards about how you should be farming your goats.",
        "counting from zero instead of one, doesn't apply to anything goat farmers do and looks stupid. hexadecimal is unheard of.",
        "when you sell a goat, you don't need to export it to a format that will be understood by the buyer's ancient goat-reading software.",
        "all your stuff will still work when you buy your 100th goat, and your 256th goat, and your 65,536th goat...",
        "people don't walk up to goat farmers at parties and whine about how they just got a french alpine and don't know how to milk it.",
        "nobody can go through your goat and get you in trouble for what they find in there.",
        "you don't have to administer a \"user acceptance test\" when you deliver goat cheese.",
        "you don't need any special utilities to delete a goat that is not empty.",
        "you don't need or want goats on your desktop, or shortcuts to goats on your desktop. most goat farmers don't have desktops.",
        "nothing a goat farmer does requires a mouse. if you have mice you get a cat.",
        "goat farmer error messages: goat not found; goat dead; goat not awake; too soon after last milking; billy goat detected. that's about all. you don't need silly numbers for these, and you don't need to look them up anywhere or check them out at goat.com.",
        "there are no read-only oats. there are no hidden or system goats.",
        "you don't need to mail anyone a core dump from a goat to fix a problem. the only time you would do this is to cause a problem.",
        "a goat that doesn't know what time it is will work just fine.",
        "a goat that is not y2k compliant will simply think it's not y2k. this is doesn't even require documentation.",
        "if your spouse doesn't authorize the purchase of a new goat, you simply encourage your goats to make one from existing parts.",
        "a goat doesn't have enough fingers to press <shift><shift><ctrl><alt><esc>",
        "goats don't argue about it being another goats problem. they just kick each others ass.",
        "if a goat had to document every time it took a shit, we would be out of forests.",
        "goats don't give a shit about email.",
        "the only way a goat can deliver an 'application' is through it's ass.",
        "goats can't get there benefits revoked they are just made into goat steaks for dinner.",
        "a goat farmer doesn't have to provide documentation on his goat's ablility to produce milk after the year 2000.",
        "goateng.",
        "macintosh goat users will not make fun of you because your goat is more problematic & complicated than the goat they just bought.",
        "goat farmers who voted for perot have pretty much the same type of goat as everyone else, so they can go back to arguing about politics like they were doing before 1984.",
        ],
    "internet-slow": [
        "solar flares",
        "goat ate the coax",
        "backhoe brought down us-east-1",
        "boat anchor broke a cable",
        "piracy",
        "someone pressed the big red button",
        "big ball of wibbly-wobbly timey-wimey stuff",
        "zayo! zaaaayo, latency come and me wanna go home",
        "capitalism",
        "furry convention",
        "datacenter caught fire again",
        "everyone restarted their phones at the same time because facebook was down"
    ]
}
